### ISSUE TITLE
How do I make keyboard work with Advanced monitors?

### ISSUE THREAD

**Issue by TabbyCatface** [tom5454/Toms-Peripherals#11]
Not yet utilizing GPU, just wanted to test keyboard with a bigger monitor, as advertised, and can't figure how to make a keyboard do anything. Please help? Can it connect to programs run on a monitor? Should I manually program in support for the keyboard?

**Comment by TabbyCatface** [comment]
Let's say I opened a lua prompt on an advanced monitor. I connected the keyboard as a peripheral to the computer. I click on it, then click on the monitor -> it does nothing. What's next?

**Comment by tom5454** [comment]
You have to connect the keyboard to the computer using wired modems, and call setFireNativeEvents(true) on the keyboard.
Here is the example script: https://github.com/tom5454/Toms-Peripherals/blob/api/examples/inWorldMonitor.lua (This expects the keyboard on top of the computer)

**Comment by TabbyCatface** [comment]
Thank you, thank you, thank you! Nice to know you've got examples in the repository.
