### ISSUE TITLE
New help with the keyboard

### ISSUE THREAD

**Issue by RusticVoid** [tom5454/Toms-Peripherals#19]
How do i connect the keyboard to the monitor and use it as a normal computer?

**Comment by tom5454** [comment]
The keyboard is a peripheral, you connect it to the computer with a wired modem or use the keyboard dongle for the wireless version.
If you use my monitors the  there is a terminal emulator script in the examples: https://github.com/tom5454/Toms-Peripherals/tree/api/examples
With CC monitors you can use the inWorldMonitor script instead.
