### ISSUE TITLE
Repository does not build.

### ISSUE THREAD

**Issue by IAteMinecraft** [tom5454/Toms-Peripherals#21]
After I cloned the repository. I found that it needed `'local:IntegratedDynamics:1.18.2-1.13.3'`, but of course I could not find where to get that.

after commenting it out, the project would not build because `com.tom.peripherals.gpu`, `com.tom.peripherals.api` and `com.tom.peripherals.math` does not exist.

**Comment by tom5454** [comment]
You have to download the api project https://github.com/tom5454/Toms-Peripherals/tree/api and put into the `TomsPeripherals` folder. Put it next to the main project folder. If you would like to build the fabric version you have to change the source set to point at the Forge folder.
