### ISSUE TITLE
How to use the keyboard??????

### ISSUE THREAD

**Issue by 7Wdev** [tom5454/Toms-Peripherals#23]
I donwloaded the mod, and I placed an advanced computer and a monitor on top and a keyboard in front of it. the keyboard just isnt activating the monitor or controlling it...
![image](https://github.com/user-attachments/assets/569d155c-6cb8-4aa9-8b7b-7c5c5fea5cc7)

**Comment by tom5454** [comment]
You have to connect your keyboard with wired modem and network cables.
And you have to run a small program for the keyboard and monitor to work.
It's in the example code repo:
https://github.com/tom5454/Toms-Peripherals/blob/api/examples/inWorldMonitor.lua
