### ISSUE TITLE
Right click and scroll wheel functionality with keyboard block

### ISSUE THREAD

**Issue by AnonymousLightbulb** [tom5454/Toms-Peripherals#6]
Am using 1.18.2, big modpack, but also tested without any mods other than cc:tweaked and this one, when I use the keyboard left clicking the screen works, but right clicking and typing don't.

**Comment by Kittenhugger213** [comment]
was using advanced moniter btw

**Comment by Kittenhugger213** [comment]
Update: used part of your example code, typing works, but right click and scroll wheel functionality is missing

**Comment by tom5454** [comment]
You have to use my monitors with the GPU block for full mouse support.

The advanced monitor only detects a right clicking on the monitor in world. The keyboard just simulates right clicking while the GUI is open.

**Comment by Kittenhugger213** [comment]
Is there a way to make a gpu display the output of normal code?

**Comment by tom5454** [comment]
You have to write a cc terminal emulator, that can display on the GPU monitors.

**Comment by Kittenhugger213** [comment]
Do you know by any chance if one already exists or would be hard to code?

**Comment by tom5454** [comment]
I uploaded a terminal emulator to the examples:
https://github.com/tom5454/Toms-Peripherals/blob/api/examples/termEmuTest.lua
