### ISSUE TITLE
can you make an example of displaying a simple image using the gpu?

### ISSUE THREAD

**Issue by TheoCGaming** [tom5454/Toms-Peripherals#7]

**Comment by Hxhnchxn** [comment]
Almost everything is copied from the examples.
`local gpu = peripheral.wrap("tm_gpu_5")
gpu.refreshSize()
gpu.setSize(64)
local of = io.open("/valley.png", "rb")
local b = of._handle.read(1)
local imgBin = {}
while b do
    imgBin[#imgBin + 1] = ("<I1"):unpack(b);
    b = of._handle.read(1)
end
local image = gpu.decodeImage(table.unpack(imgBin))
gpu.drawImage(1,1,image.ref())
gpu.sync()`
